"""Reconciliation tests: verify the OpenAI tools schema the model receives
accurately exposes every tool defined in the tool registry, and every tool
has a handler.

With native tool calling, the model learns about tools through the ``tools``
parameter of the completion request (generated by ``tool_defs_to_openai_tools``),
not through the system prompt. These tests catch the class of bug where a tool
handler supports parameters (like read_file's start_line/end_line) but the
schema never tells the model about them — so the model can't use them.
"""

import re
import sys
from pathlib import Path

# Ensure the src package is importable
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from harness.tool_registry import (
    TOOL_DEFS,
    TOOL_BY_NAME,
    tool_defs_to_openai_tools,
)


def _schema_by_name() -> dict[str, dict]:
    """Return {tool_name: function_schema} from the generated OpenAI tools."""
    schema: dict[str, dict] = {}
    for entry in tool_defs_to_openai_tools():
        func = entry["function"]
        schema[func["name"]] = func
    return schema


def _schema_params(func: dict) -> dict[str, bool]:
    """Extract {param_name: is_required} from a function schema."""
    params_schema = func.get("parameters", {})
    properties = params_schema.get("properties", {})
    required = set(params_schema.get("required", []))
    return {name: (name in required) for name in properties}


# ── Registry → OpenAI schema reconciliation ───────────────────────

# Tools handled directly in the agent loop, not via tool_handlers
_AGENT_LOOP_TOOLS = {"end_turn", "manage_todos", "introspect"}


class TestRegistryToSchema:
    """Every tool in TOOL_DEFS must appear in the generated OpenAI tools schema."""

    def test_every_registry_tool_in_schema(self):
        schema = _schema_by_name()
        missing = [td.name for td in TOOL_DEFS if td.name not in schema]
        assert not missing, (
            f"Tools in registry but missing from the OpenAI tools schema: {missing}\n"
            f"tool_defs_to_openai_tools() must emit a function for every tool."
        )

    def test_every_schema_tool_exists_in_registry(self):
        schema = _schema_by_name()
        extra = [name for name in schema if name not in TOOL_BY_NAME]
        assert not extra, (
            f"Tools in the schema but missing from registry: {extra}"
        )

    def test_every_schema_tool_has_description(self):
        schema = _schema_by_name()
        missing = [name for name, func in schema.items() if not func.get("description")]
        assert not missing, (
            f"Tools in schema with no description (model needs it): {missing}"
        )


class TestParamReconciliation:
    """Every registry param must appear in the schema, and vice versa."""

    def test_every_registry_param_in_schema(self):
        schema = _schema_by_name()
        missing = []
        for td in TOOL_DEFS:
            func = schema.get(td.name, {})
            schema_params = _schema_params(func)
            for p in td.params:
                if p.name not in schema_params:
                    missing.append(f"{td.name}.{p.name}")
        assert not missing, (
            f"Params defined in registry but undocumented in schema: {missing}\n"
            f"The model cannot use parameters it doesn't know about."
        )

    def test_required_params_match(self):
        """Required-ness in registry matches required-ness in the schema."""
        schema = _schema_by_name()
        mismatches = []
        for td in TOOL_DEFS:
            func = schema.get(td.name, {})
            schema_params = _schema_params(func)
            for p in td.params:
                if p.name in schema_params and p.required != schema_params[p.name]:
                    expected = "required" if p.required else "optional"
                    actual = "required" if schema_params[p.name] else "optional"
                    mismatches.append(
                        f"{td.name}.{p.name}: registry={expected}, schema={actual}"
                    )
        assert not mismatches, (
            "Required-ness mismatch between registry and schema:\n"
            + "\n".join(f"  - {m}" for m in mismatches)
        )

    def test_no_extra_schema_params(self):
        """Schema doesn't expose params that don't exist in the registry."""
        schema = _schema_by_name()
        extras = []
        for td in TOOL_DEFS:
            func = schema.get(td.name, {})
            schema_params = _schema_params(func)
            registry_param_names = {p.name for p in td.params}
            for sp_name in schema_params:
                if sp_name not in registry_param_names:
                    extras.append(f"{td.name}.{sp_name}")
        assert not extras, (
            f"Params in schema but missing from registry: {extras}"
        )


class TestToolDispatchCoverage:
    """Every tool in the registry must be dispatchable (has a handler)."""

    def test_every_tool_has_dispatch_handler(self):
        """Check that _dispatch_tool in cline_agent.py handles every registry tool."""
        agent_path = Path(__file__).resolve().parent.parent / "src" / "harness" / "cline_agent.py"
        source = agent_path.read_text(encoding="utf-8")

        # Find all tool names referenced in _dispatch_tool elif/if chain
        dispatch_re = re.compile(
            r'tool\.name\s*==\s*["\'](\w+)["\']'
        )
        dispatched = set(dispatch_re.findall(source))

        missing = []
        for td in TOOL_DEFS:
            # end_turn is handled outside _dispatch_tool
            if td.name == "end_turn":
                continue
            if td.name not in dispatched:
                missing.append(td.name)
        assert not missing, (
            f"Tools in registry with no dispatch handler in cline_agent.py: {missing}"
        )

    def test_every_tool_handler_method_exists(self):
        """Check that ToolHandlers class has methods for handler-based tools."""
        from harness.tool_handlers import ToolHandlers

        # Map from tool_name to expected method name on ToolHandlers
        # Tools handled in the agent loop directly are excluded.
        _METHOD_MAP = {
            "read_file": "read_file",
            "write_to_file": "write_file",
            "replace_in_file": "replace_in_file",
            "replace_between_anchors": "replace_between_anchors",
            "execute_command": "execute_command",
            "list_files": "list_files",
            "search_files": "search_files",
            "check_background_process": "check_background_process",
            "stop_background_process": "stop_background_process",
            "list_background_processes": "list_background_processes",
            "analyze_image": "analyze_image",
            "web_search": "web_search",
            "mcp_list_tools": "mcp_list_tools",
            "mcp_search_tools": "mcp_search_tools",
            "mcp_call_tool": "mcp_call_tool",
            "retrieve_tool_result": "retrieve_tool_result",
        }
        missing = []
        for tool_name, method_name in _METHOD_MAP.items():
            if not hasattr(ToolHandlers, method_name):
                missing.append(f"{tool_name} → ToolHandlers.{method_name}()")
        assert not missing, (
            f"Tool handler methods missing: {missing}"
        )


class TestPromptToolParamAcceptance:
    """Verify the tool handler actually reads the params the prompt documents."""

    def test_read_file_handler_uses_start_end_line(self):
        """The exact bug we missed: read_file supports start_line/end_line
        but the prompt didn't document them. Verify the handler reads them."""
        import inspect
        from harness.tool_handlers import ToolHandlers

        source = inspect.getsource(ToolHandlers.read_file)
        assert "start_line" in source, "read_file handler doesn't reference start_line"
        assert "end_line" in source, "read_file handler doesn't reference end_line"

    def test_execute_command_handler_uses_background(self):
        """execute_command has an optional 'background' param."""
        import inspect
        from harness.tool_handlers import ToolHandlers

        source = inspect.getsource(ToolHandlers.execute_command)
        assert "background" in source, "execute_command handler doesn't reference background"

    def test_search_files_handler_uses_file_pattern(self):
        """search_files has an optional 'file_pattern' param."""
        import inspect
        from harness.tool_handlers import ToolHandlers

        source = inspect.getsource(ToolHandlers.search_files)
        assert "file_pattern" in source, "search_files handler doesn't reference file_pattern"


if __name__ == "__main__":
    import pytest
    sys.exit(pytest.main([__file__, "-v"]))
